export const CONFIG = {
    initialSpeed: 0.1 as const,
    maxSpeed: 0.8 as const,
    speedIncreaseRate: 0.01 as const,
    playerSize: 1 as const,
    playerColor: 0x00ff00 as const,
    playerVelocity: 0.3 as const,
    playerBoundaryX: 4 as const,
    trackWidth: 10 as const,
    trackLength: 1000 as const,
    trackCurveFactor: 0.05 as const,
    trackCurveAmplitude: 2.0 as const,
    trackColor: 0x2a2a5a as const,
    orbSize: 0.4 as const,
    orbColor: 0xffff00 as const,
    obstacleSize: 2 as const,
    obstacleColor: 0xff0000 as const,
    spawnDistanceMin: -100 as const,
    spawnDistanceMax: -150 as const,
    orbSpawnChance: 0.02 as const,
    obstacleSpawnChance: 0.01 as const,
    starCount: 2000 as const,
    planetCount: 5 as const,
    dustCount: 500 as const,
    starSize: 2 as const,
    planetSizeMin: 10 as const,
    planetSizeMax: 30 as const,
    orbScoreValue: 10 as const,
    cameraFov: 75 as const,
    cameraNear: 0.1 as const,
    cameraFar: 1000 as const,
    cameraPosition: { x: 0, y: 10, z: 30 } as const,
    cameraLookAt: { x: 0, y: 0, z: 0 } as const,
  };